### ISSUE TITLE
Design Duck Feature Assets

### ISSUE THREAD

**Issue by janine9vn** [python-discord/aaaaAAAA#2]
To support procedural generation of ducks #1, we'll actually need the assets themselves!

This is to generate the facial features, hats, scarves, and other duck components that will be used to create different and distinguishable ducks.

The assets should be in svg and png format ideally, and should all be the same size so that they can easily just be superimposed on each other. No need to place things in the right place, we just use transparancy to our advantage.

**Comment by lemonsaurus** [comment]
The MVP for this is done now. You can find instructions and all components in https://github.com/python-discord/aaaaAAAA/tree/main/img/duck-builder
