### ISSUE TITLE
Splash screen and a main menu

### ISSUE THREAD

**Issue by mbaruh** [python-discord/aaaaAAAA#22]
Should start with a splash screen, like the pydis logo fading in and out

A main menu. Concept by lemon:
![image](https://user-images.githubusercontent.com/18114431/112901863-fc54d900-90ed-11eb-8832-cc16490452d7.png)

- Should have background music
- Sound when hovering over an option

Bonus point:
- The option slightly grows when you hover over it
- The ducks in the background move. This will be easier to do when we have the game logic down, and might be deferred to a future issue.
- Make the tongue wiggle

**Comment by lemonsaurus** [comment]
We haven't solved all the bonuses here, but the main points are fixed. Let's move the low priority stuff into another issue.
