### ISSUE TITLE
Splash Screen Design Assets

### ISSUE THREAD

**Issue by janine9vn** [python-discord/aaaaAAAA#3]
We need design assets for the splash screen introducing the game and for players to press "Start" or "Enter".

It should maybe be related to the game itself... but maybe not? Who knows.

Overall, this should take into account things like buttons, background, our team banner/logo, the framework we're using logo, etc.

**Comment by lemonsaurus** [comment]
![image](https://user-images.githubusercontent.com/2098517/112878145-df0d1400-90c7-11eb-88e7-c2cdd058c1e2.png)

I'm thinking the title screen can be something like this.

**Comment by lemonsaurus** [comment]
Solved by 3c5e917
