### ISSUE TITLE
Create Main Character Lemoji

### ISSUE THREAD

**Issue by janine9vn** [python-discord/aaaaAAAA#4]
Let's design our main character! We can give some special details here and spend a bit more time on it.

This will be a lemoji and our lemoji needs to be a cop/police and "official" looking.

**Comment by lemonsaurus** [comment]
![supercop](https://user-images.githubusercontent.com/2098517/113289074-02b2a300-92f0-11eb-86f8-c3820f605fd2.png)

I did this, and he looks like this!

I'll make a square version to add as a lemoji in the community now.

**Comment by lemonsaurus** [comment]
Added to the community as `:lemon_police:`
