### ISSUE TITLE
Create List of "Rule" Requirements

### ISSUE THREAD

**Issue by janine9vn** [python-discord/aaaaAAAA#8]
Each day the player is presented with a list of rules/requirements that they need to check each ducky for. They start off easy and with a smaller amount and as the game progresses, the rules get more detailed/complicated and/or there are more of them.

We need to actually create these rules! The rules should be concerning the duckies and their attributes/features:
- Let's start out with the physical traits (i.e. no duckys with glasses, no blue scarves, no beards, etc)
- The ducks may carry something on themselves as an attribute that they either need or is not allowed (i.e. has a sword, must have a day-pass to utopia, has invasive algae that isn't allowed)
- Maybe the ducky has some non PEP-8 compliant code?? (This could be for a challenge round, where each ducky has a code snippet and you need to check for PEP8 compliance)

Generally, these rules come flying down from the heavens as new instructions for the day. Ideally, they should be kept simple and explainable.

Maybe these requirements should have an additional tag associated such as "easy, normal, hard/code" to facilitate easier random selection day-to-day.

**Comment by bast0006** [comment]
Random ideas: Albino duckies (full white/full black), ugly duckies (fuchsia?)

**Comment by MrGrote** [comment]
PEP-8 problems:
	lowercase class names
	missing white space around operator
	uppercase function names
	single line if statements
	comparison to None using ==
	end line with semicolon
	multiple leading # for a comment

**Comment by lemonsaurus** [comment]
Now that we have a big computer monitor in the bottom right, we could probably display the code on this! As long as it's a fairly short snippet, it seems fine.

![image](https://user-images.githubusercontent.com/2098517/113471135-a28c4000-945a-11eb-8cf0-370413bf5416.png)

**Comment by lemonsaurus** [comment]
at font size 26, I can fit 26 characters across 7 lines.

..which is probably enough.

**Comment by lemonsaurus** [comment]
As for physical attribute rules:
- No hats
- No beards
- No ninjas
- No weapons
- Hats required
- ROYAL POND: Only kings allowed, deny anyone withou a crown.
- RACISM MODE: Only blue ducks allowed!
