### ISSUE TITLE
Wooden Rule Sign Dropping From the Sky mechanic

### ISSUE THREAD

**Issue by janine9vn** [python-discord/aaaaAAAA#9]
Each day a wooden sign will drop from above with the new list of requirements. We need the mechanic to drop down the wooden sign at the beginning of the day and when the user clicks on it, it shows a pop-up screen with the list of rules and requirements for that day. 

Ideally this pop-up should be able to stay on the screen as the player processes each ducky. It should also be moveable. It would be nice if it was scaleable, but that is a bonus feature and not a necessity.

**Comment by ChrisLovering** [comment]
Maybe a small impact/impale asset would be good too. We place it at the impact site, so it looks like the sign is impaled in the ground.

**Comment by lemonsaurus** [comment]
I'm now thinking the rules will be displayed on computer monitors in the bottom right pane, in the pond protectors "control station". We will put a sign next to the pond that just says Duck Pond. No need to have it drop from the heavens.
